const ACTION_TYPES = {
    GET_MESSAGE_ACTION: 'GET_MESSAGE_ACTION',
    GET_MESSAGE_REQUEST: 'GET_MESSAGE_REQUEST',
    GET_MESSAGE_SUCCESS: 'GET_MESSAGE_SUCCESS',
    GET_MESSAGE_ERROR: 'GET_MESSAGE_ERROR',

    NEW_MESSAGE_ACTION: 'NEW_MESSAGE_ACTION',
    NEW_MESSAGE_REQUEST: 'NEW_MESSAGE_REQUEST',
    NEW_MESSAGE_SUCCESS: 'NEW_MESSAGE_SUCCESS',
    NEW_MESSAGE_ERROR: 'NEW_MESSAGE_ERROR',
};

export default ACTION_TYPES;